### ISSUE TITLE
Word embeddings

### ISSUE THREAD

**Issue by edponce** [edponce/DoyleInvestigators2#3]
Use Gensim's  Word2Vec to build vector embedding for a given corpus.
Take advantage of Edmon's demo code.
Include the capability of saving/loading the vector embeddings so that we do not need to recompute them always.

**Comment by fabianfallasmoya** [comment]
I worked on the task "Use Gensim's Word2Vec to build vector embedding for a given corpus". I uploaded here in Github one draft of code (I tried to comment every step) for the tasks we need to perform.

@quanqhow can you work on the task "Include the capability of saving/loading the vector embeddings so that we do not need to recompute them always." ?
